version: '3.7'
services:
  mysqldb:                      # 服务的名称
    restart: always           # 总是随容器启动
    image: mysql # 镜像的位置 
    container_name: mysqldb   # 容器的名称
    ports:                    # 映射容器端口
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'roto-123456'
      TZ: 'Asia/Shanghai'                # 时区
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    volumes:
      - ./mysql/data:/var/lib/mysql  #映射数据卷
      #- /data/web/cloud/docker/mysql/conf:/etc/mysql/conf.d 
      #- /data/web/cloud/docker/mysql/logs:/logs
    networks:
      - default
      - myout-network
  tocmat:                      # 服务的名称
    restart: always            # 总是随容器启动
    image: dordoka/tomcat      # 镜像的位置
    container_name: tomcat8    # 容器的名称
    ports:                     # 映射容器端口
      - 8816:8080
    environment:
      TZ: Asia/Shanghai
    volumes:
      - D:./webapps:/opt/tomcat/webapps
      - D:./logs:/opt/tomcat/logs
    networks:
      - default
networks:
  myout-network:
    external: true  # 使用外部网络true