# redis
# docker network create ctos-network
version: '3.7'
services:
  redis:
    container_name: 'redis'
    image: 'redis:latest'
    hostname: 'ctos.javazz.com'
    restart: always
    #command: redis-server /usr/local/etc/redis/redis.conf
    command: redis-server --requirepass 123!@#
    #command: redis-server /etc/redis/redis.conf
    #enviroment:
    # - REDIS_HOSTS=local:redis:6379
    ports:
     - 6379:6379
    volumes:
     #- ./config:/usr/local/etc/redis
     - ./data:/data
     - ./redis.conf:/etc/redis/redis.conf
    #command: redis-server /usr/local/etc/redis/redis.conf
networks:
  default:
    external:
      name: ctos-network
